In [9]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
data1
data2 = np.array(data1)

In [7]:
data1 * 2

[6, 7.5, 8, 0, 1, 6, 7.5, 8, 0, 1]

In [10]:
data2 * 2

array([ 12.,  15.,  16.,   0.,   2.])

In [4]:
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [7]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

(2, 4)

In [8]:
arr2.ndim
# Number of array dimensions.
# http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html

2

In [9]:
arr2.shape

(2, 4)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int64')

In [12]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [14]:
np.empty((2,3,2))

array([[[  0.00000000e+000,  -3.10503637e+231],
        [  2.96439388e-323,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   8.34402697e-309]]])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# 4.1.2
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [15]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [17]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [20]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [21]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [25]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2d[2]

array([4, 5, 6])

In [35]:
arr2d[2] = [7,8,9]
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr2d[2][1]
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [38]:
data1 = np.array([1,2,3,4])
data1

array([1, 2, 3, 4])

# 슬라이스 색인

In [50]:
data1[1:3]

array([2, 3])

In [45]:
arr2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

### 4.1.5 불리언 색인

In [57]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], 
      dtype='<U4')

In [59]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [65]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [58]:
data = np.random.randn(7,4)
data

array([[-0.43754536, -0.72739274, -2.85598525, -0.07564153],
       [-0.97105385, -0.43543385, -0.11390207,  1.19404886],
       [ 0.41447662, -0.1198855 ,  0.53168131,  0.8853581 ],
       [-1.46759228,  0.77305677,  0.72910347,  0.28868637],
       [ 2.98558866, -2.11807124,  0.52400427, -0.14014695],
       [-0.2915325 , -2.12179094, -0.38776042,  0.4621458 ],
       [-0.65956168,  1.64587388,  0.34182186,  1.3009589 ]])

In [66]:
mask = (names == 'Bob')
data[mask]

array([[-0.43754536, -0.72739274, -2.85598525, -0.07564153],
       [-1.46759228,  0.77305677,  0.72910347,  0.28868637]])

In [62]:
data[names == 'Bob', 2:]

array([[-2.85598525, -0.07564153],
       [ 0.72910347,  0.28868637]])

In [69]:
data[data < 0] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.19404886],
       [ 0.41447662,  0.        ,  0.53168131,  0.8853581 ],
       [ 0.        ,  0.77305677,  0.72910347,  0.28868637],
       [ 2.98558866,  0.        ,  0.52400427,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.4621458 ],
       [ 0.        ,  1.64587388,  0.34182186,  1.3009589 ]])

### 4.1.6 팬시 색인

In [71]:
arr = np.empty((8,4))
arr

array([[  0.00000000e+000,   0.00000000e+000,   2.12215770e-314,
          1.48219694e-323],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          6.36598737e-314],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   1.44013662e+149,   2.16227853e-314,
          2.17483844e-314],
       [  3.29100392e+276,   2.17440001e-314,   2.17483840e-314,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   9.88131292e-324,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   2.12215769e-314,
          2.47032823e-323]])

In [72]:
for i in range(8):
    arr[i] = i

In [73]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [74]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [75]:
arr[[-1,-2]]

array([[ 7.,  7.,  7.,  7.],
       [ 6.,  6.,  6.,  6.]])

In [76]:
arr[[1,3,5]][:,[0,1,2]]

array([[ 1.,  1.,  1.],
       [ 3.,  3.,  3.],
       [ 5.,  5.,  5.]])

 ### 4.1.7 배열 전치와 축 바꾸기 

In [79]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [81]:
np.sqrt(data1)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [82]:
np.max(data1)

4

In [83]:
np.maximum(data1, data1*2)

array([2, 4, 6, 8])

In [84]:
data1

array([1, 2, 3, 4])

In [89]:
%pylab
import matplotlib.pyplot as plt

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [90]:
points = np.arange(-5, 5, 0.01) # -5 ~ 5. step 0.01
points

array([ -5.00000000e+00,  -4.99000000e+00,  -4.98000000e+00,
        -4.97000000e+00,  -4.96000000e+00,  -4.95000000e+00,
        -4.94000000e+00,  -4.93000000e+00,  -4.92000000e+00,
        -4.91000000e+00,  -4.90000000e+00,  -4.89000000e+00,
        -4.88000000e+00,  -4.87000000e+00,  -4.86000000e+00,
        -4.85000000e+00,  -4.84000000e+00,  -4.83000000e+00,
        -4.82000000e+00,  -4.81000000e+00,  -4.80000000e+00,
        -4.79000000e+00,  -4.78000000e+00,  -4.77000000e+00,
        -4.76000000e+00,  -4.75000000e+00,  -4.74000000e+00,
        -4.73000000e+00,  -4.72000000e+00,  -4.71000000e+00,
        -4.70000000e+00,  -4.69000000e+00,  -4.68000000e+00,
        -4.67000000e+00,  -4.66000000e+00,  -4.65000000e+00,
        -4.64000000e+00,  -4.63000000e+00,  -4.62000000e+00,
        -4.61000000e+00,  -4.60000000e+00,  -4.59000000e+00,
        -4.58000000e+00,  -4.57000000e+00,  -4.56000000e+00,
        -4.55000000e+00,  -4.54000000e+00,  -4.53000000e+00,
        -4.52000000e+00,

In [91]:
xs, ys = np.meshgrid(points, points)

In [92]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [93]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [95]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [102]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [101]:
z1 = z.copy()
z1[ (z1 < 0.99) | (z1 > 1.0) ]=1
plt.close()
plt.imshow(z1, cmap=plt.cm.gray)
plt.title("Image plot of $\sqrt{x^2+y^2}=1$ ")

In [104]:
#np.where(a==0, 2, -2)

NameError: name 'a' is not defined

In [105]:
np.mean()

TypeError: mean() missing 1 required positional argument: 'a'

In [106]:
np.amean()

AttributeError: 'module' object has no attribute 'amean'

In [107]:
a.cumsum()

NameError: name 'a' is not defined

## 4.5 선형대수

In [108]:
x = np.array([[1., 2., 3.], [4.,5.,6.]])
y = np.array([[6.,23.], [-1,7], [8,9]])
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [109]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [110]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [111]:
np.dot(x, np.ones(3))

array([  6.,  15.])

# 응용1

In [112]:
cls = np.array(['B','C','X','D','I','F','O','H','W','A'])
cnt = np.array([108755682,47551903,5999736,3827665,2253434,2046654,1863277,1600870,1115500,181732],dtype=np.float64)

In [113]:
mask = (cls == 'C') | (cls == 'D') | (cls == 'A')
mask

array([False,  True, False,  True, False, False, False, False, False,  True], dtype=bool)

In [116]:
cnt[mask]

array([ 47551903.,   3827665.,    181732.])

In [124]:
np.sum(cnt[mask])

51561300.0

In [126]:
cnt[mask] / np.sum(cnt[mask]) * 100

array([ 92.22401879,   7.42352307,   0.35245814])

In [127]:
cnt[mask] / cnt[mask].sum() * 100

array([ 92.22401879,   7.42352307,   0.35245814])

# 응용2

## 문제
http://cfile236.uf.daum.net/original/16045E49513D441B0E9283

## 참고자료
http://www.mathteacher.pe.kr/mt_11/mt_11_09.htm

In [128]:
import numpy as np

In [129]:
a = np.array([ [5, 4 ], [ 8, 4 ] ])
b = np.array( [364, 544])

In [130]:
from numpy.linalg import inv, pinv

In [131]:
inv(a)

array([[-0.33333333,  0.33333333],
       [ 0.66666667, -0.41666667]])

In [132]:
a.dot(inv(a))

array([[ 1.,  0.],
       [ 0.,  1.]])

In [133]:
a.dot(inv(a)).dot(a)

array([[ 5.,  4.],
       [ 8.,  4.]])

In [134]:
inv(a).dot(b)

array([ 60.,  16.])

In [135]:
np.linalg.solve(a,b)

array([ 60.,  16.])

In [136]:
help(np.linalg.solve)

Help on function solve in module numpy.linalg.linalg:

solve(a, b)
    Solve a linear matrix equation, or system of linear scalar equations.
    
    Computes the "exact" solution, `x`, of the well-determined, i.e., full
    rank, linear matrix equation `ax = b`.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Coefficient matrix.
    b : {(..., M,), (..., M, K)}, array_like
        Ordinate or "dependent variable" values.
    
    Returns
    -------
    x : {(..., M,), (..., M, K)} ndarray
        Solution to the system a x = b.  Returned shape is identical to `b`.
    
    Raises
    ------
    LinAlgError
        If `a` is singular or not square.
    
    Notes
    -----
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    The solutions are computed using LAPACK routine _gesv
    
    `a` must be square and of full-rank, i.e., all rows (or, equivalently,
    columns) must be linearly independent; if either is not true

### 유사 역행렬

In [137]:
a1 = np.array([ [1, 2], [2, 4]])
# ad - bc = 1*4 - 2*2 = 0
inv(a1)

LinAlgError: Singular matrix

In [138]:
pinv(a1)

array([[ 0.04,  0.08],
       [ 0.08,  0.16]])

In [139]:
a1.dot(pinv(a1))

array([[ 0.2,  0.4],
       [ 0.4,  0.8]])

In [140]:
a1.dot(pinv(a1)).dot(a1)

array([[ 1.,  2.],
       [ 2.,  4.]])

### 선형회귀분석

In [141]:
comp = np.array(['삼성전자', '현대차', '한국전력', '삼성물산', 'SK하이닉스'])

In [4]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [12]:
# [ 시가총액, 2/4분기매출, 2/4분기영업이익, 자산


data = np.array([[1870701, 485375, 68979, 2316909],
                 [356847, 228216, 17509,  1536161],
                 [310389, 136718, 20880, 1700829],
                 [300658, 13115, 391,  87722 ],
                 [273364, 46386, 13755, 284637 ]]
         )

                 


In [16]:
lr = LinearRegression()
X = data[:,1:]
print(X.shape)
X

(5, 3)


array([[ 485375,   68979, 2316909],
       [ 228216,   17509, 1536161],
       [ 136718,   20880, 1700829],
       [  13115,     391,   87722],
       [  46386,   13755,  284637]])

In [18]:
y = data[:,0]
print(y.shape)
print(y)

(5,)
[1870701  356847  310389  300658  273364]


In [11]:
model = lr.fit(X, y)
model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [150]:
model.coef_

array([  2.09225307,  21.93717933,  -0.35896193])

In [151]:
#학습한 모델로 다시 예측해본 시가총액
# [ 삼성전자, 현대차, 한국전력, 삼성물산, SK하이닉스 ] 순
model.predict(X)

array([ 1831056.46781415,   444166.94926873,   267570.66652241,
         138535.04415561,   430629.8722391 ])

In [152]:
# 모델의 정확도 평가. 1 이 perfect
model.score(X,y)

0.96820534203116981

In [153]:
# 모델의 정확도 평가. 분산값. 클수록 정확도가 나쁜 모델
np.mean((model.predict(X) - y) ** 2)

12409255907.434668